server:
  port: 8082

spring:
  application:
    name: shippingandhandling
  datasource:
    url: jdbc:mysql://localhost:3306/shippingAndHandling
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
